fix old HIP_PATCH_VERSION and build with embedded protobuf
rocm-arch/python-pytorch-rocm pull request #13
Opened 2020-12-22 21:59 UTC by nquest

2020-12-22 22:53 UTC, acxz requested changes
I'm glad you got the pytorch build working again! We haven't had it building since rocm 3.7/8 I wanna say.

A couple of nitpicks and I'd like you to make an upstream issue (and link it back here or vice versa), but once you're done with that let's merge this boi in!

2020-12-22 22:53 UTC, acxz commented on PKGBUILD
>              'SKIP')
Since the patch is not a PR, let's get a checksum for it.

2020-12-22 22:53 UTC, acxz commented on PKGBUILD
> -  export VERBOSE=1
Let's keep this the same as the "upstream" pytorch pkgbuild: https://github.com/archlinux/svntogit-community/blob/packages/python-pytorch/trunk/PKGBUILD

2020-12-22 22:53 UTC, acxz commented on PKGBUILD
> +  export USE_OPENCV=ON
whoa you got pytorch to build with this flag on?! That's great. I had trouble with it which is why it has been flagged off for so long.

2020-12-22 22:53 UTC, acxz commented on PKGBUILD
> +  patch -Np1 -i "${srcdir}"/fix-hip-version.patch
I feel like there is def a better fix for this issue then the commenting out some lines. For now let's keep it as a building pkgbuild is much happier than a failing one. We'll keep this patched and should report the issue/build error upstream. Can you do so before I merge this in, to ensure upstream knows about?

2020-12-22 23:35 UTC, nquest commented on PKGBUILD
> +  patch -Np1 -i "${srcdir}"/fix-hip-version.patch
[Pytorch issue](https://github.com/pytorch/pytorch/issues/49768#issue-773315510)
Ughh.. how to mention issue in another repo&

2020-12-22 23:42 UTC, acxz commented on PKGBUILD
> +  patch -Np1 -i "${srcdir}"/fix-hip-version.patch
Exactly like that. Usually you just want to do the link and github will autoformat it, instead of manually doing the `[]()` format.

2020-12-22 23:57 UTC, nquest commented on PKGBUILD
> -  export VERBOSE=1
updated

2020-12-23 00:43 UTC, acxz commented
@nquest can you address https://github.com/rocm-arch/python-pytorch-rocm/issues/12#issuecomment-749822228 before this gets merged in?

2020-12-23 00:44 UTC, acxz commented on PKGBUILD
> -  export VERBOSE=1
This still seems to show a diff.

2020-12-23 11:57 UTC, nquest commented on PKGBUILD
> -  export VERBOSE=1
Sorry, fighting against squashing and force-push, Now all ok.

2020-12-23 17:15 UTC, acxz approved these changes
looking good, thx for iterating @nquest !

2020-12-23 17:15 UTC, merged